### ISSUE TITLE
Backspace Android keypad

### ISSUE THREAD

**Issue by marcialpaulg** [mattpass/ICEcoder#630] opened 2016-04-07 11:57 UTC
Hi. when i tap backspace in android keypad, it will delete the character and create a new line at the top of the line.

I am using icecoder for almost 2 years but in sometime cases, we need to develope codes in our phones.

Thank you for developing such awesome project.

**Comment by mattpass** [comment] 2016-04-08 08:20
Hey @marcialpaulg - glad you like ICEcoder  :-)

I saw the issue you mentioned a while back but haven't seen that for months now. What version of Android are you using - plus is it the stock browser or another such as Chrome? Also are you using the latest ICEcoder (v5.4)? Also let me know the kind of file you're editing? If I can recreate the problem I can fix it.

It may be a CodeMirror issue (it's the core editing component in ICEcoder) - do you have the same problem using http://codemirror.net/demo/complete.html

**Comment by marcialpaulg** [comment] 2016-04-08 14:41
Hi, thank you for the fast response.

Android version: 4.4.4
Browser: latest chrome version
IceCoder version: 5.3 (i already used the 5.4 in the demo, having same
issue)
File type: php

Yes, same thought ... I didn't have issue using the demo of codemirror.

Have a nice day ☺

**Comment by mattpass** [comment] 2016-04-13 21:04
@marcialpaulg Mmmmm, it's a very weird bug. I could get to recreate it on Chrome on Android 4.4 but not using backspace, it was typing any character. However, out of 10 serious attempts to reproduce the same issue, could only get it to happen once. No idea what gets it into that state. Will keep trying to reliably create the same issue so I can establish the cause and bugfix.

Do you know under what exact steps it will show this issue?

**Comment by marcialpaulg** [comment] 2016-04-13 23:47
I login to icecoder, open my recent opened files by tapping "ok" in the
popup, then open an another file from drawer and bug happens.

**Comment by mattpass** [comment] 2016-08-12 13:53
Played around with this a bit more and found it can be realiably produced by just typing into a blank document. The letters seem slightly smaller than usual and stack 1 ontop another on same line till you focus somewhere else in the document or press return or space. Weird!

**Comment by mattpass** [comment] 2016-08-12 14:36
Think there's a batch of glitchy issues with CodeMirror on Android phones under both the stock browser and Chrome. Have logged my findings there as it'd be CodeMirror owner to correct really. Hope he gets to the bottom of the issues. Closing this issue tho and watch the issue on other repo for updates: https://github.com/codemirror/CodeMirror/issues/4161

**Closed** 2016-08-12 14:40 UTC
Labels: Bug
