### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by AK-101111** [mattpass/ICEcoder#307] opened 2013-09-01 09:08 UTC
After installation, pointing at http://mydomain.com/_coder/ redirects to lib/settings.php throwing an Internal Server Error.
The full error is:
"The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, webmaster@mydomain.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."

Could not find any server error logs. 
thanks,

-Alex

ps. tried it on a different server and installs flawlessly

**Comment by bfishman** [comment] 2016-03-29 03:12
I believe I may be having a related error, but will open a new issue if you'd prefer. The `755` trick doesn't work, unfortunately. After upgrading to 5.4 (although this happened during 5.2 -> 5.3 as well), going to `<internal ip address>/ICEcoder` yields the following: 

```
Not Found

The requested URL /ICEcoder/settings.php was not found on this server.
```

Same thing if i visit `<external ip address>/ICEcoder`.  But visiting `localhost/ICEcoder` works perfectly, bringing up the application.

This seems like an Apache config issue to me, but I poked around in settings to find where the failure was occurring. See the following code from settings.php:

```
// On mismatch of settings file to system, rename to .old and reload
If ($ICEcoderUserSettings["versionNo"] != $ICEcoderSettings["versionNo"]) {
        //die("__FILE__ : ".__FILE__."<br>dirname: ".dirname(__FILE__)."<br>settingsFile: ".$settingsFile);
        rename(dirname(__FILE__)."/".$settingsFile,dirname(__FILE__)."/".str_replace(".php",".old",$settingsFile));
        //die("this is reached");
        header("Location: settings.php");
        //die("this is not reached");
        echo "<script>window.location='settings.php';</script>";
        die('Found old settings file, reloading...');
}
```

The top (commented) `die` prints:

```
__FILE__ : /home/bfishman/webroot/ICEcoder/lib/settings.php
dirname: /home/bfishman/webroot/ICEcoder/lib
settingsFile: config-sourcedreams_com.php
```

The second `die` is reached, but the third is not. So the `header()` function is somehow failing.

Any idea what would cause this, or how to fix it?

**Comment by bfishman** [comment] 2016-03-29 04:00
After a bit more digging, the contents of `$ICEcoderUserSettings`, prior to the above code is:

Array ( [previousFiles] => [configCreateDate] => 1459222891 )

Thus it's missing any 'versionNo' field. 

I commented out the entire settings mismatch block above, and the next failure occurred at 

```
// Determin our allowed IP addresses
$allowedIP = false;
for($i=0;$i<count($_SESSION['allowedIPs']);$i++) {
        if ($_SESSION['allowedIPs'][$i]==$_SERVER["REMOTE_ADDR"]||$_SESSION['allowedIPs'][$i]=="*") {
                $allowedIP = true;
        }
}
```

I believe this is because the $ICEcoder array does not contain any 'allowedIPs' --- even though the `config___users-template.php` file specifies an array with "*" as that field's value.

**Note:** while poking around (having removed all the debugging `die()`s, it seems that while `config-localhost.php` is fully-formed file, any of the other files, such as `config-127.0.0.1.php` are all empty and read-only. Could that be relevant?

**Comment by bfishman** [comment] 2016-03-29 18:02
@mattpass would you like this opened in a new issue?

**Comment by mattpass** [comment] 2016-03-29 18:50
Hi @bfishman - yes, it'd be great if this could be added as new issue please as this one is closed. Could maybe make reference to this issue (#307) if you think there's relevant info here.

I'll then look into this. I haven't tried accessing ICEcoder under an IP TBH, always under a domain or localhost so maybe something not quite right that could be tweaked to run under an IP. If you can file an issue I'll look into it! :-)

**Comment by bfishman** [comment] 2016-03-29 19:19
Thanks Matt, will do so shortly. As a clarification, `<my domain>/ICEcoder` gives the same error.

**Comment by L3CC** [comment] 2016-04-25 00:54
I might be a bit late on this one, but here are my 5 cents...
We can reproduce this error if we copy the files to a different server instead of doing a normal installation.  The "config-*php" files will have the wrong domain in the name and that seems to produce this issue. If we rename the config files to match the new server's name, the problem disappears.

**Comment by mattpass** [comment] 2016-04-25 09:24
Thanks @L3CC - that certainly might be a problem. I'll look into a more graceful solution here, even if it's simply alerting you to the fact it can't find/create a config-*.php file for the current domain.

**Comment by mattpass** [comment] 2016-07-31 12:06
Think this issue ended up covered by a new issue (#622) that was logged and handled, so closing.

**Closed by mattpass** 2016-07-31 12:06 UTC
Labels: Bug, Version 5.7
