### ISSUE TITLE
Login Redirects with PHP-FPM

### ISSUE THREAD

**Issue by Dunky13** [mattpass/ICEcoder#542] opened 2015-02-23 10:59 UTC
When running Apache + PHP5-FPM you get Too Many Redirect errors in login. I found it comes because it looks for: !strpos($_SERVER['SCRIPT_NAME'],"lib/login.php") on line 166 in ./lib/settings.php
PHP5-FPM sets $_SERVER['SCRIPT_NAME'] to /php5-fcgi - you should consider making this fool proof.
If I find a solution to changing the SCRIPT_NAME to the proper settings I will post the solution on: https://mwent.info/blog

**Comment by mattpass** [comment] 2015-02-23 21:42
Thanks for the report. No one else has reported this issue, but if you find a solution please let us know. It will need to be on GitHub tho as we won't look to your blog. This is the place to log and discuss issues - thanks.

**Comment by Dunky13** [comment] 2015-02-24 07:52
Matt,

I agree solutions to this problem should be discussed here - but this is a generic problem. SCRIPT_NAME is changes by PHP-FPM with not only your application. So a generic solution is not only for this Github.

An application specific solution would be to change SCRIPT_NAME to PATH_INFO, it seems to work for me - yet I'm not sure if it is a proper solution. Or if possible PHP_SELF?

**Comment by mattpass** [comment] 2015-02-24 08:03
Thanks - not used PATH_INFO myself as yet, but have used PHP_SELF in the past. There's also __FILE__ - can look into these and see which one is a better alternative and why SCRIPT_NAME may be a problem on some setups. Mmmm.

**Comment by Dunky13** [comment] 2015-03-24 09:20
Matt, I don't know if you've found a solution already, but I've been working with dirname(__FILE__) lately. Maybe something to look into ;-)

**Comment by mattpass** [comment] 2015-03-24 21:20
No solution as yet as a lot of testing to be done to ensure it works on all setups. I'm a big fan of ```dirname(__FILE__)``` tho so that could be a real solution here.

**Comment by mattpass** [comment] 2015-04-25 11:09
Have made some other changes which I think actually may be the cause of this. If you happen to pull the latest code from this repo and still run into issues, please reopen the issue, but I'm hoping it's now fixed (I use PHP-FPM also and seems to work fine).

**Closed by mattpass** 2015-04-25 11:09 UTC
Labels: Bug, Version 5
